name: Release 

on:
  push:
    tags:
      - '*'

jobs:
  build-linux:
    runs-on: ubuntu-latest

    env:
      VERNAME: ${{ github.head_ref || github.ref_name }}

    steps:
    - uses: actions/checkout@v3
   
    - name: Setup 
      run: |
        sudo apt-get update && sudo apt-get install -y make ca-certificates
        sudo update-ca-certificates

    - name: Build
      run: |
        echo "${{ env.GITHUB_REF_NAME }} > .version"
        make lin_bin VERSION=${{ env.GITHUB_REF_NAME }}

    - name: Save artifact
      uses: actions/upload-artifact@v3
      with:
        name: linbin
        path: autoortho_lin_*.bin

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: autoortho_lin_*.bin


  build-windows:
    runs-on: windows-latest

    env:
      VERNAME: ${{ github.head_ref || github.ref_name }}

    steps:
    - uses: actions/checkout@v3
   
    - uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Setup 
      run: |
          #choco --yes install winfsp
          python -m pip install -U pytest 
          # Windows OS package install ecosystem is sketchy and broken.  Just test min stuff ...
          python -m pip install -U -r requirements-win.txt
          python -m pip install -U -r requirements-build.txt

    - name: Build
      run: |
        echo "${{ env.GITHUB_REF_NAME }} > .version"
        make win_exe VERSION=${{ env.GITHUB_REF_NAME }}
        make win_zip ZIP="7z a" VERSION=${{ env.GITHUB_REF_NAME }}

    - name: Save artifact
      uses: actions/upload-artifact@v3
      with:
        name: winbin
        path: |
          AutoOrtho_*.exe
          autoortho_win_*.zip

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          AutoOrtho_*.exe
          autoortho_win_*.zip

